DROP TABLE IF EXISTS `inmueble`;

  CREATE TABLE `inmuebles`.`inmueble` (
  `IdInmueble` INT NOT NULL AUTO_INCREMENT,
  `NumCredito` VARCHAR(80) DEFAULT '' NOT NULL,
  `NombreDeudor` VARCHAR(100) DEFAULT '' NOT NULL ,
  `ApellidosDeudor` VARCHAR(100) DEFAULT '' NOT NULL ,
  `TipoAdquisicion` VARCHAR(20) DEFAULT '' NOT NULL,
  `IdReoBan` INT DEFAULT 0 NOT NULL,
  `CuentaCat` VARCHAR(100) DEFAULT '' NOT NULL,
  `NumFolioReal` VARCHAR(80) DEFAULT '' NOT NULL,
  `IdEtapa` INT DEFAULT 0 NOT NULL,
  `IdEstado` INT DEFAULT 0 NOT NULL,
  `IdMunicipio` INT DEFAULT 0 NOT NULL,
  `Calle` VARCHAR(80) DEFAULT '' NOT NULL,
  `CodigoPostal` VARCHAR(20) DEFAULT '' NOT NULL,
  `M2superficie` decimal(14,4) DEFAULT 0 NOT NULL,
  `M2construccion` decimal(14,4) DEFAULT 0 NOT NULL,
  `MontoDeuda` decimal(20,4) DEFAULT 0 NOT NULL,
  `MontoMin` decimal(20,4) DEFAULT 0 NOT NULL,
  `MontoVenta` decimal(20,4) DEFAULT 0 NOT NULL,
  `NumExpediente` VARCHAR(80) DEFAULT '' NOT NULL,
  `ComentarioRegPub` VARCHAR(300) DEFAULT '' NOT NULL,
  `ComentarioExpJudicial` VARCHAR(300) DEFAULT '' NOT NULL,
  `EstatusInmueble` VARCHAR(30) DEFAULT '' NOT NULL,
  `Estatus` INT DEFAULT 171 NOT NULL ,
  PRIMARY KEY (`IdInmueble`));